### ISSUE TITLE
Navbar and Footer

### ISSUE THREAD

**Issue by DevBigEazi** [Mentor-Ntech/DLT-Website#16]
Implement the new design for the navbar and footer and link the route of each page to the navbar and footer link accordingly.
[figma](https://www.figma.com/file/MVcfb7C1GjLC5tMrTy9loy/DLT-AFRICA?node-id=0%3A1&mode=dev)

Pls utilize the existing components

**Comment by Mentor-Ntech** [comment]
hey guys,,i will like to work on Navbar and footer
