### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by DevBigEazi** [Mentor-Ntech/DLT-Website#17]
Add the new input to the form and connect it to backend
[Figma](https://www.figma.com/file/MVcfb7C1GjLC5tMrTy9loy/DLT-AFRICA?node-id=0%3A1&mode=dev)

**Comment by Kenny001-spec** [comment]
i want to work on Registration form

**Comment by DevBigEazi** [comment]
Already assigned to myself, kindly choose another issue
