### ISSUE TITLE
Courses Hero sections

### ISSUE THREAD

**Issue by DevBigEazi** [Mentor-Ntech/DLT-Website#19]
Implement the hero section [design](https://www.figma.com/file/MVcfb7C1GjLC5tMrTy9loy/DLT-AFRICA?node-id=0%3A1&mode=dev) for the four courses pages.

**Comment by Kenny001-spec** [comment]
i want to work on the hero section

**Comment by DevBigEazi** [comment]
@kehinde01 No problem
