### ISSUE TITLE
Courses details section

### ISSUE THREAD

**Issue by DevBigEazi** [Mentor-Ntech/DLT-Website#20]
Implement the design as seen in this picture from the [figma](https://www.figma.com/file/MVcfb7C1GjLC5tMrTy9loy/DLT-AFRICA?node-id=709%3A3200&mode=dev) file. Do this for each of the course pages.
<img width="437" alt="courses details" src="https://github.com/Mentor-Ntech/DLT-Website/assets/102731426/952f1bf0-ada0-4879-a3f1-0ddb1bc3f753">

Pls strictly use the existing FAQ component and props for the accordion

**Comment by Soliu-Ahmad** [comment]
i want to work on this
course details
